// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ihnzzpbiigfubnsbmkuh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlobnp6cGJpaWdmdWJuc2Jta3VoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNjQ4ODYsImV4cCI6MjA3NDY0MDg4Nn0.RdCrQbqO42FMyJ9P16jRciB4-jOfhqWh3imU8r0PWU8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});